### PR TITLE
Search results follow

### PR DESCRIPTION
**Pull request by RyanTG**
Ok, I think this is aight.

### CODE REVIEW

**Comment by scottwainstock** [comment]
@RyanTG I rebased a clean master branch against this and I see a lot of test failures...

Was your branch rebased against master?

```
rspec ./spec/features/location_machine_xrefs_controller_spec.rb:30 # LocationMachineXrefsController add machines Should add by id
rspec ./spec/features/location_machine_xrefs_controller_spec.rb:207 # LocationMachineXrefsController machine descriptions should let me add a new machine description
rspec ./spec/features/locations_controller_spec.rb:19 # LocationsController confirm location lets you click a button to update the date_last_updated
rspec ./spec/features/locations_controller_spec.rb:30 # LocationsController confirm location displays no username when it was last updated by a non-user
rspec ./spec/features/locations_controller_spec.rb:79 # LocationsController remove machine removes a machine from a location
rspec ./spec/features/locations_controller_spec.rb:166 # LocationsController initial search by passed in param by_machine_group_id
rspec ./spec/features/locations_controller_spec.rb:241 # LocationsController initial search by passed in param by_machine_id
rspec ./spec/features/locations_controller_spec.rb:269 # LocationsController update_metadata does not save data if any formats are invalid - website and phone
rspec ./spec/features/locations_controller_spec.rb:336 # LocationsController update_metadata allows users to update a location metadata - stubbed out spam detection
rspec ./spec/features/locations_controller_spec.rb:358 # LocationsController update_metadata allows users to update a location metadata - TWICE
rspec ./spec/features/locations_controller_spec.rb:393 # LocationsController update_desc does not save spam
rspec ./spec/features/locations_controller_spec.rb:465 # LocationsController update_desc allows users to update a location description - skips validation
rspec ./spec/models/region_spec.rb:32 # Region#generate_daily_digest_comments_email_body should generate a string containing all machine comments from the day
rspec ./spec/models/region_spec.rb:52 # Region#generate_daily_digest_removals_email_body should generate a string containing all machine removals from the day
```

**Comment by RyanTG** [comment]
I merged master into it, but didn't rebase. Guess that was the wrong thing to do...

On April 15, 2017 1:12:06 PM PDT, Scott Wainstock <notifications@github.com> wrote:
>@RyanTG I rebased a clean master branch against this and I see a lot of
>test failures...
>
>Was your branch rebased against master?
>
>```
>rspec ./spec/features/location_machine_xrefs_controller_spec.rb:30 #
>LocationMachineXrefsController add machines Should add by id
>rspec ./spec/features/location_machine_xrefs_controller_spec.rb:207 #
>LocationMachineXrefsController machine descriptions should let me add a
>new machine description
>rspec ./spec/features/locations_controller_spec.rb:19 #
>LocationsController confirm location lets you click a button to update
>the date_last_updated
>rspec ./spec/features/locations_controller_spec.rb:30 #
>LocationsController confirm location displays no username when it was
>last updated by a non-user
>rspec ./spec/features/locations_controller_spec.rb:79 #
>LocationsController remove machine removes a machine from a location
>rspec ./spec/features/locations_controller_spec.rb:166 #
>LocationsController initial search by passed in param
>by_machine_group_id
>rspec ./spec/features/locations_controller_spec.rb:241 #
>LocationsController initial search by passed in param by_machine_id
>rspec ./spec/features/locations_controller_spec.rb:269 #
>LocationsController update_metadata does not save data if any formats
>are invalid - website and phone
>rspec ./spec/features/locations_controller_spec.rb:336 #
>LocationsController update_metadata allows users to update a location
>metadata - stubbed out spam detection
>rspec ./spec/features/locations_controller_spec.rb:358 #
>LocationsController update_metadata allows users to update a location
>metadata - TWICE
>rspec ./spec/features/locations_controller_spec.rb:393 #
>LocationsController update_desc does not save spam
>rspec ./spec/features/locations_controller_spec.rb:465 #
>LocationsController update_desc allows users to update a location
>description - skips validation
>rspec ./spec/models/region_spec.rb:32 #
>Region#generate_daily_digest_comments_email_body should generate a
>string containing all machine comments from the day
>rspec ./spec/models/region_spec.rb:52 #
>Region#generate_daily_digest_removals_email_body should generate a
>string containing all machine removals from the day
>```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scottwainstock/pbm/pull/668#issuecomment-294315331

-- 
Sent while mobile.

**Comment by RyanTG** [comment]
Actually I didn't use the merge command, even. I did pull upstream master, and fixed the conflicts. I should have researched that more.

On April 15, 2017 1:12:06 PM PDT, Scott Wainstock <notifications@github.com> wrote:
>@RyanTG I rebased a clean master branch against this and I see a lot of
>test failures...
>
>Was your branch rebased against master?
>
>```
>rspec ./spec/features/location_machine_xrefs_controller_spec.rb:30 #
>LocationMachineXrefsController add machines Should add by id
>rspec ./spec/features/location_machine_xrefs_controller_spec.rb:207 #
>LocationMachineXrefsController machine descriptions should let me add a
>new machine description
>rspec ./spec/features/locations_controller_spec.rb:19 #
>LocationsController confirm location lets you click a button to update
>the date_last_updated
>rspec ./spec/features/locations_controller_spec.rb:30 #
>LocationsController confirm location displays no username when it was
>last updated by a non-user
>rspec ./spec/features/locations_controller_spec.rb:79 #
>LocationsController remove machine removes a machine from a location
>rspec ./spec/features/locations_controller_spec.rb:166 #
>LocationsController initial search by passed in param
>by_machine_group_id
>rspec ./spec/features/locations_controller_spec.rb:241 #
>LocationsController initial search by passed in param by_machine_id
>rspec ./spec/features/locations_controller_spec.rb:269 #
>LocationsController update_metadata does not save data if any formats
>are invalid - website and phone
>rspec ./spec/features/locations_controller_spec.rb:336 #
>LocationsController update_metadata allows users to update a location
>metadata - stubbed out spam detection
>rspec ./spec/features/locations_controller_spec.rb:358 #
>LocationsController update_metadata allows users to update a location
>metadata - TWICE
>rspec ./spec/features/locations_controller_spec.rb:393 #
>LocationsController update_desc does not save spam
>rspec ./spec/features/locations_controller_spec.rb:465 #
>LocationsController update_desc allows users to update a location
>description - skips validation
>rspec ./spec/models/region_spec.rb:32 #
>Region#generate_daily_digest_comments_email_body should generate a
>string containing all machine comments from the day
>rspec ./spec/models/region_spec.rb:52 #
>Region#generate_daily_digest_removals_email_body should generate a
>string containing all machine removals from the day
>```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scottwainstock/pbm/pull/668#issuecomment-294315331

-- 
Sent while mobile.

**Comment by RyanTG** [comment]
Is this how I replicate this?

git checkout -b upstream/master master_clean
git checkout search_results_follow
git rebase master_clean



On April 15, 2017 1:12:06 PM PDT, Scott Wainstock <notifications@github.com> wrote:
>@RyanTG I rebased a clean master branch against this and I see a lot of
>test failures...
>
>Was your branch rebased against master?
>
>```
>rspec ./spec/features/location_machine_xrefs_controller_spec.rb:30 #
>LocationMachineXrefsController add machines Should add by id
>rspec ./spec/features/location_machine_xrefs_controller_spec.rb:207 #
>LocationMachineXrefsController machine descriptions should let me add a
>new machine description
>rspec ./spec/features/locations_controller_spec.rb:19 #
>LocationsController confirm location lets you click a button to update
>the date_last_updated
>rspec ./spec/features/locations_controller_spec.rb:30 #
>LocationsController confirm location displays no username when it was
>last updated by a non-user
>rspec ./spec/features/locations_controller_spec.rb:79 #
>LocationsController remove machine removes a machine from a location
>rspec ./spec/features/locations_controller_spec.rb:166 #
>LocationsController initial search by passed in param
>by_machine_group_id
>rspec ./spec/features/locations_controller_spec.rb:241 #
>LocationsController initial search by passed in param by_machine_id
>rspec ./spec/features/locations_controller_spec.rb:269 #
>LocationsController update_metadata does not save data if any formats
>are invalid - website and phone
>rspec ./spec/features/locations_controller_spec.rb:336 #
>LocationsController update_metadata allows users to update a location
>metadata - stubbed out spam detection
>rspec ./spec/features/locations_controller_spec.rb:358 #
>LocationsController update_metadata allows users to update a location
>metadata - TWICE
>rspec ./spec/features/locations_controller_spec.rb:393 #
>LocationsController update_desc does not save spam
>rspec ./spec/features/locations_controller_spec.rb:465 #
>LocationsController update_desc allows users to update a location
>description - skips validation
>rspec ./spec/models/region_spec.rb:32 #
>Region#generate_daily_digest_comments_email_body should generate a
>string containing all machine comments from the day
>rspec ./spec/models/region_spec.rb:52 #
>Region#generate_daily_digest_removals_email_body should generate a
>string containing all machine removals from the day
>```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scottwainstock/pbm/pull/668#issuecomment-294315331

-- 
Sent while mobile.

**Comment by RyanTG** [comment]
I... nearly have it. I rebased (what's the point of rebasing this? so the merge history is clean and not filled with four years of commits? this concept is new to me). I found it to be messy and confusing. In the end, the tests pass, but... the functionality is broken. I think I screwed up fixing a conflict. argh.

**Comment by RyanTG** [comment]
https://developers.google.com/maps/documentation/javascript/events
Cool event demo.

It doesn't explain what triggers mouseup. Is it when you release the mouse click?

**Pull request merged**
