### PR TITLE
show num of machines in results - fixes # 1138

### PR DESCRIPTION
**Pull request by RyanTG**

### CODE REVIEW

**Comment by RyanTG** [comment]
What is happening with Travis?
````
     Selenium::WebDriver::Error::SessionNotCreatedError:
       session not created: This version of ChromeDriver only supports Chrome version 74
         (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.4.0-101-generic x86_64)
````

**Comment by RyanTG** [comment]
Running them locally:
```
Finished in 12 minutes 3 seconds (files took 8.1 seconds to load)
459 examples, 0 failures

[Coveralls] Outside the CI environment, not sending data.
Running RuboCop...
Inspecting 135 files
.......................................................................................................................................

135 files inspected, no offenses detected

```

**Comment by scottwainstock** [comment]
@RyanTG This is cool now?

**Comment by RyanTG** [comment]
Y

**Pull request merged**
