### PR TITLE
styles for ipad; removed hover and added click to menu

### PR DESCRIPTION
**Pull request by RyanTG**
Since ipads don't count as mobile devices, the menu wasn't triggering because it only had hover behavior and not click behavior (on mobile, it had click behavior). But I couldn't get it to work with hover AND click behavior, so I removed the hover behavior.

### CODE REVIEW

**Comment by RyanTG** [comment]
This isn't really failing. I think it's just failing here because of that timestamp bug, or because phantomjs crashed in travis.

**Comment by scottwainstock** [comment]
@RyanTG I'm getting merge conflicts here. I think I know how to handle the _header.html.haml one, but it's not clear to me how to resolve the mediaqueries.css. Would you mind rebasing on origin auth_required and fixing those conflicts?

**Comment by RyanTG** [comment]
No problem.

**Comment by RyanTG** [comment]
https://github.com/scottwainstock/pbm/pull/522/commits/239b824d832e7c28bee243322b72e90540e00763 Commit description: If a user is not logged, then when they hover over the "confirm location" div, the cursor does not become a pointer; and if there is no "location last updated" message, then that div is not there (previously, there was an empty box - and for those non-logged in users, the function of it was probably unclear).

I fixed conflicts and committed. I then did db:migrate (forgot to do it first), which produced changes to schema.

Bundle install is really finicky. First off I get fetch errors. Second off, it will successfully update, BUT THEN it turns out that it totally failed to install half of them. I just realized it did this. I'll see what comes of it after it's actually successful. Coverage dropped in this pull (although it says, "remained the same" even though it clearly dropped).

**Comment by RyanTG** [comment]
Reset my schema file via "git checkout upstream/auth_required db/schema.rb". Why the fuck is coverage at 43%?

**Comment by RyanTG** [comment]
@scottwainstock If you have any thoughts about the coverage, let me know. I don't understand it. If I compare builds in travis - my recent one with your last merged one - I'm running the same amount of tests, and my tests are passing. Not sure why my coverage would be so low, then.

**Comment by scottwainstock** [comment]
@RyanTG This happened with Abby's PR, I'm going to take a look into it today. I doubt it's anything meaningful, no one added a ton of code or removed tests or anything.

**Comment by RyanTG** [comment]
Ok thanks. Not sure why, but at 1am last night I paused The Matrix Reloaded to merge and commit. I was tired and baffled by that coverage report.

**Comment by scottwainstock** [comment]
It's cool to write code while watching TM:R.

Yeah see check this out: https://coveralls.io/builds/8038991

Look at the "all" tab. Clearly those files exist... so, maybe coveralls is
just having some problem right now. I'll keep half an eye on it.

**Comment by RyanTG** [comment]
Yeah, I felt really cool. I should have put on my sunglasses while coding and watching it. That would have been the ultimate.

**Pull request merged**
