### PR TITLE
styled closest locations and rest of menu

### PR DESCRIPTION
**Pull request by RyanTG**
Not perfect, but it's a start. This menu stuff is tough.

### CODE REVIEW

**Comment by RyanTG** [comment]
wait, getting some test fails...

**Comment by RyanTG** [comment]
Nevermind. They're all ipdb_id related fails. Nothing to do with this commit..

**Comment by scottwainstock** [comment]
K. Have you rake db:migrate d lately?

**Comment by RyanTG** [comment]
I did a couple weeks ago, but not since ipdb_id was added. I'll do it now.

**Pull request merged**
