### PR TITLE
Auth required

### PR DESCRIPTION
**Pull request by RyanTG**
Lemme know if this is all fucked up. I don't know why this PR is showing older commits. I merged before I made my changes!

### CODE REVIEW

**Comment by RyanTG** [comment]
Favicons are a huge hassle. So I used a gem (in development) to generate them.

**Comment by RyanTG** [comment]
Tell me if I should change this file from html.erb to html.haml https://github.com/scottwainstock/pbm/pull/535/commits/0a314dbdc924d6aab2283e38690885e021d84e7a#diff-6d6aa3f5062493659bb3c500a59d11b3

**Comment by scottwainstock** [comment]
I think you're fine to leave them as erb. Those can co-exist with haml.

**Comment by RyanTG** [comment]
Once this is merged and on staging, I'll check to make sure I didn't break any forms. I removed the captcha from the location submission. And for logged in users, I hid the name/email fields on the admin contact form (since we get that data anyway). I wanted to remove the captcha on the admin contact form for logged in users, but I couldn't figure that out.

Also, right now the location submission form checks to make sure people aren't entering a website address in the Machines field. But I don't know if that check is relevant anymore, given that only logged in users can fill it out. So I think I'll take that out next.

**Comment by scottwainstock** [comment]
@RyanTG Deployed.

**Pull request merged**
