### PR TITLE
hr in menu; mobile adjustments; changed encourage_profile to get_profile

### PR DESCRIPTION
**Pull request by RyanTG**

### CODE REVIEW

**Comment by scottwainstock** [comment]
"get_" is kind of a reserved phrase in Ruby. It's going to cause us trouble
in the future... so, I was using encourage_ instead.

**Comment by RyanTG** [comment]
Oh ok. I'll change it back. I just wanted to use a word that was shorter than "encourage"

and the tests passed on my computer!

**Comment by scottwainstock** [comment]
Yeah something really weird is up with coveralls... since the gem upgrade
it's been going nuts. I'll have to look into it. I'd just trust what's on
your local machine for now.

**Comment by RyanTG** [comment]
Changed it to "inspire_profile"... it's short and almost rhymes.
Also, in my last commit I didn't get change the name of the haml file! I did ctrl-r and changed the contents of the files, but not the file name itself. DUH.

Committing when local test is done. gemfile.lock is listed as a changed file, and I'm not committing it. Dunno why it's there.

**Comment by RyanTG** [comment]
Every other time I run the test I get two errors. 

Like:
2) MachineScoreXrefsController add machine scores - no auth does not allow you to enter a score if you are not logged in
     Failure/Error: where(region_id: r.id)

     NoMethodError:
       undefined method `id' for nil:NilClass

Followed by a big list of ruby files...

**Pull request merged**
