### PR TITLE
Updated the devise confirmation flash message

### PR DESCRIPTION
**Pull request by RyanTG**

### CODE REVIEW

**Comment by RyanTG** [comment]
Once it's on staging, I'll check and make sure that it all works correctly.

**Comment by scottwainstock** [comment]
Deployed.

**Comment by RyanTG** [comment]
Huh, I can't create a new account. So I reverted the changes in these commits on my local, and it still won't work! 

The error is "username can't be blank; email can't be blank" - but they aren't blank! And then after clicking Join the url resolves to http://pinballmapstaging.herokuapp.com/users

**Comment by RyanTG** [comment]
Feeeexed. I broke it many commits ago (though I swear I've created a new account since then).

**Pull request merged**
