### PR TITLE
update readme, and clear high score input after submit

### PR DESCRIPTION
**Pull request by RyanTG**
I need to take a closer look at the sort order for high scores. Seems wacky?

### CODE REVIEW

**Comment by RyanTG** [comment]
Check failed because it's looking for ruby 2.3.4. Is that something I have to change on my end (note: I'm using 2.3.4 on my local, and I ran the tests and they all passed EXCEPT for the two "daily digest of emails" ones. I'm not sure if those are intermittent or real problems.

Also, in case you missed it, I asked a question to you @scottwainstock on this issue (but I asked when editing a comment, so you may not have been pinged): https://github.com/scottwainstock/pbm/issues/671#issuecomment-295014072

**Comment by scottwainstock** [comment]
@RyanTG That failure is intermittent. I'll get back with you on the other stuff.

**Comment by scottwainstock** [comment]
@RyanTG Sorry, not super clear to me the situation here.. this is ready to be deployed?

**Comment by RyanTG** [comment]
Yes.

Before I made this commit, I asked you if there was any specific reason why the form wasn't being cleared after someone submits a score. You said there wasn't (or actually, you asked the same question back to me...?).

So my unclear response was me trying to say, "ok then. this commit fixes the issue." I should have been clearer.

**Pull request merged**
