### PR TITLE
changed slash to vertical line; optimized mobile header for 8 billion…

### PR DESCRIPTION
**Pull request by RyanTG**
… different phones

### CODE REVIEW

**Comment by RyanTG** [comment]
Tell me what you think about these new icons. 
And on the "confirm location" icon, I added mouseover behavior (another icon). There are 10 different ways to do mouseovers, and I wasn't sure what was best. I went with a simple javascript method, as you can see in the _render_desc file. I also preloaded the hover image using js, and I put that in the same _render_desc file rather than the main application.js file. Tell me if that's a mistake, or if any of this could be done better. 

I would like to add mouseovers to all of them. Ideally, I would also add a new icon onclick. But those items already have click behavior attributed to them, and I don't want to mess with that. Another way to do mouseovers/click behavior is with css. I guess I'll try that next. At first I tried to create a sprite that contains all three states, and the image just jumps from one to the next based on what the mouse is doing. But it was too difficult to create a perfect sprite, so I gave up. But I guess I can keep them as separate files.

**Comment by RyanTG** [comment]
Nevermind. I figured out how to make sprites using ImageMagick. It worked well. So now it's using css on the confirm location button. I'll do the other after I rest.

**Comment by RyanTG** [comment]
I'll fix the test. I'm having trouble running them because phantomjs keeps crashing.

**Comment by RyanTG** [comment]
Still can't finish the dang tests. But I think I figured out where they were breaking.

**Comment by scottwainstock** [comment]
Looks good to me.

**Comment by RyanTG** [comment]
If you think they're too large, I can make them smaller. I can't tell... they're sorta big. But maybe that's ok.

**Pull request merged**
