### PR TITLE
fixed broken map

### PR DESCRIPTION
**Pull request by RyanTG**

### CODE REVIEW

**Comment by RyanTG** [comment]
Sorry about breaking that :<

**Comment by scottwainstock** [comment]
@RyanTG Well wait, hang on... is it broken right now? It was broken earlier when I pushed my google maps api key thing. I reverted that.

**Comment by RyanTG** [comment]
The live site is still showing the line that I removed in this commit https://github.com/scottwainstock/pbm/pull/772/files

**Comment by scottwainstock** [comment]
@RyanTG No, what I'm saying is that I think *MY* code broke the site, not yours. Is the live site, right now, broken? It doesn't look broken to me.

**Comment by RyanTG** [comment]
It's currently broken in firefox, but not chrome.

**Comment by scottwainstock** [comment]
@RyanTG Ah, OK. Reverting.

I like that footer though... and I like that "more/less map" thing too.

**Comment by RyanTG** [comment]
Reverting? Just merge my fix!

**Comment by scottwainstock** [comment]
@RyanTG Oh well yeah, that's what I mean.

**Comment by scottwainstock** [comment]
@RyanTG Does it work now? I want to put my api thing back in... but I don't want to confuse the issue.

**Comment by RyanTG** [comment]
I just got worried for a second that you were about to revert my whole pull request.

Anyway, yes that one issue is currently resolved.

I am finding additional minor issues, though:
- If I load ALL in the Eugene region, the map pins are underneath the results container (doesn't happen if I load ALL in portland).
- Not all of the map tiles are loading. I thought I fixed this, but it's still there - though the map tile that's not loading is much smaller now...

**Pull request merged**
