### PR TITLE
fixed a javascript mistake for editing meta and description

### PR DESCRIPTION
**Pull request by RyanTG**
Not too happy with the tests.

This `find('#location_detail_location_#{@location.id} .location_meta .meta_image').click` produces a fail, while this `find('.location_meta span.meta_image').click` does not. 

But using `#location_detail_location_#{@location.id}` in the selector works fine for descriptions. I don't get why it doesn't work for the meta span. The error is: 
`The browser raised a syntax error while trying to evaluate css selector "#location_detail_location_\#{@location.id} .location_meta .meta_image"`

### CODE REVIEW

**Comment by scottwainstock** [comment]
@RyanTG This doesn't look like it fixed things... at least on my end.

**Comment by RyanTG** [comment]
Meta boxes for multiple locations are opening at the same time? I'm not seeing that anymore. Hmm...

**Comment by scottwainstock** [comment]
No, I'm saying that this isn't letting me edit a location's meta and/or
comment twice. Not without reloading the page. Here's a test I wrote that
fails, and it doesn't work when I try it by hand. Maybe it's something on
my end? Does this test pass for you?

Put this at line 349 of spec/features/locations_controller_spec.rb

    it 'allows users to update a location metadata - TWICE' do
      stub_const('ENV', 'RAKISMET_KEY' => 'asdf')

      expect(Rakismet).to receive(:akismet_call).and_return('false')

      t = FactoryGirl.create(:location_type, name: 'Bar')
      o = FactoryGirl.create(:operator, region: @location.region, name:
'Quarterworld')

      visit '/portland/?by_location_id=' + @location.id.to_s

      find('.location_meta span.meta_image').click
      fill_in("new_website_#{@location.id}", with: 'http://www.foo.com')
      click_on 'Save'

      sleep 1

      expect(Location.find(@location.id).website).to eq('http://www.foo.com
')
      expect(page).to_not have_css('div#flash_error')

      find('.location_meta span.meta_image').click
      fill_in("new_website_#{@location.id}", with: 'http://www.bar.com')
      click_on 'Save'

      sleep 1

      expect(Location.find(@location.id).website).to eq('http://www.bar.com
')
      expect(page).to_not have_css('div#flash_error')
    end

**Comment by RyanTG** [comment]
Sorry for being unclear. I stated in the issue that this commit doesn't address that bug. Instead, it just addresses that other bug you discovered last night. I think they're unrelated.

I have no idea how to fix the issue at hand. I can't figure it out.

**Comment by scottwainstock** [comment]
Ohhhhhhh, OK. Got it. Sorry, this is just me not reading carefully enough.

I'll try to handle the double edits not working.

Your code fixed the multi-open on my end. Thanks.

**Pull request merged**
