### PR TITLE
added https to google maps sensor; added home link to regional dropdo…

### PR DESCRIPTION
**Pull request by RyanTG**
…wn menu

### CODE REVIEW

**Comment by RyanTG** [comment]
I figured out why that results div wasn't loading for me on staging. It's because the staging site uses https://. But the google maps sensor we call uses http://. And the browser blocks it from loading because of some mixed media issue. I THINK I corrected it on this pull request. So if you can move this to staging when you get a chance, I can test it.

**Comment by scottwainstock** [comment]
@RyanTG There's 42 test failures here. A lot of them look kind of big. Can you take a look at it? I'm happy to fix them, but it'd help to get some commentary on why they broke.

**Comment by RyanTG** [comment]
I'll do it. sorry.

**Comment by RyanTG** [comment]
I changed the location of the search button - so I think the issue here is that the search button is not being clicked in the test. Everything that breaks is due to the results not loading. I'm trying to figure out how to solve it, though.

**Comment by RyanTG** [comment]
And by "changed the location of the search button" I mean that I wrapped it in a div called ".search_field_container" 

I'm having trouble finding where which test to add this to.

**Comment by RyanTG** [comment]
Actually, it might be due to this: https://github.com/scottwainstock/pbm/pull/505/commits/d70bb144f56693166e4d98aa7c8b91edb9b504a9#diff-b7186ba040870c69d2ae394fa317ea64L22
I'm running the test with that reverted. See you in 8 minutes.

**Comment by RyanTG** [comment]
broken pipe during the test =/ Trying again. But so far it looks like changing http to https was the issue.
I sent the staging site to Pat today to see if had any design feedback. And he couldn't load the results, due to that "mixed active content" issue. And the error is on that line of code. And the only difference between staging and live is that staging uses https. So I figured changing it the line of code to https would fix it! But, it broke all the tests, so I guess it's not that simple. If we ever change our site to https, then we may need a solution for this.

**Comment by RyanTG** [comment]
The issue is noted by others here: https://github.com/hpneo/gmaps/issues/442 (found via search)
And here's an interesting solution http://stackoverflow.com/a/30473228 which so far (tests in progress) seems to be working. If the tests pass, I'll commit it.

**Pull request merged**
