### PR TITLE
Auth required dependency updates

### PR DESCRIPTION
**Pull request by abbysmalls**
Interestingly, I've seen the spec at 
 ./spec/features/location_machine_xrefs_controller_spec.rb:843
failing since I setup the project. I'm sure that you have been running specs over the past month, and am curious if it now fails for you with my push. Will fix if so. Let me know!
 ^^^ I saw that you have CI on all branches and it failed, so I've already updated. Mysteries of the universe.

### CODE REVIEW

**Comment by scottwainstock** [comment]
@abbysmalls Thanks! I'll take a look at this over the weekend... I got slammed this week with non-PBM stuff.

**Comment by scottwainstock** [comment]
I think you ran afoul of https://github.com/scottwainstock/pbm/issues/492 ... thanks for fixing.

**Comment by scottwainstock** [comment]
@abbysmalls This looks good. One comment: I needed to downgrade aws-sdk because of this issue here: http://stackoverflow.com/questions/28374401/nameerror-uninitialized-constant-paperclipstorages3aws

... we use that gem for image uploading. It's the only (I hope) major feature of the site that's relatively untested. So, unfortunately we won't catch errors in that part of the site right now using rspec. I'll put in a tech debt issue to add more coverage to that area of the site. I've avoided it in the past because of laziness.

Thanks for all of this work! I'll push the results out to the staging server tonight.

**Comment by scottwainstock** [comment]
@abbysmalls I had to remove an unnecessary trailing } from production.rb, and now I need to revert the rest of the changes in that file. I'm getting this error message:

remote:        rake aborted!
remote:        ArgumentError: Invalid notifier 'deliver_with' defined as :deliver

If you see issues with that, let me know, but it appears to be preventing me from deploying the code in a production environment.

**Comment by scottwainstock** [comment]
@abbysmalls Actually, I don't appear to be able to get this thing to deploy to staging (production environment) at all anymore. I reverted all the changes that were made to production.rb, and I get this now:

```
remote:        Running: rake assets:precompile
remote:        [DEPRECATION] 'Rack::Attack.blacklist' is deprecated.  Please use 'blocklist' instead.
remote:        rake aborted!
remote:        NoMethodError: undefined method `new' for ExceptionNotifier:Module
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.0/lib/action_dispatch/middleware/stack.rb:43:in `build'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.0/lib/action_dispatch/middleware/stack.rb:118:in `block in build'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.0/lib/action_dispatch/middleware/stack.rb:118:in `each'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.0/lib/action_dispatch/middleware/stack.rb:118:in `inject'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.0/lib/action_dispatch/middleware/stack.rb:118:in `build'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/railties-4.1.0/lib/rails/engine.rb:498:in `app'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/railties-4.1.0/lib/rails/application/finisher.rb:36:in `block in <module:Finisher>'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/railties-4.1.0/lib/rails/initializable.rb:30:in `instance_exec'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/railties-4.1.0/lib/rails/initializable.rb:30:in `run'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/railties-4.1.0/lib/rails/initializable.rb:55:in `block in run_initializers'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/railties-4.1.0/lib/rails/initializable.rb:54:in `run_initializers'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/railties-4.1.0/lib/rails/application.rb:288:in `initialize!'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/railties-4.1.0/lib/rails/railtie.rb:194:in `public_send'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/railties-4.1.0/lib/rails/railtie.rb:194:in `method_missing'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/config/environment.rb:5:in `<top (required)>'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `require'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `block in require'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:232:in `load_dependency'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `require'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/railties-4.1.0/lib/rails/application.rb:264:in `require_environment!'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/railties-4.1.0/lib/rails/application.rb:367:in `block in run_tasks_blocks'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/sprockets-rails-2.0.1/lib/sprockets/rails/task.rb:54:in `block (2 levels) in define'
remote:        /tmp/build_7309970fa6dffcb715ac7c3f3d87a956/vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
remote:        Tasks: TOP => environment
remote:        (See full trace by running task with --trace)
```

Any ideas?

**Comment by scottwainstock** [comment]
@abbysmalls I reverted BACK to your original code... looks like maybe you forgot a 👍 
:email => { ? I'm going to try it.

**Comment by scottwainstock** [comment]
@abbysmalls Success.

**Comment by abbysmalls** [comment]
Scott! Thanks for taking care of that! I didn't realize my GitHub notifications were only going to my work address, and not personal, so I just figured y'all were busy and hadn't looked yet (I have the month off of work). Phew.

**Pull request merged**
