### PR TITLE
new style - no brown

### PR DESCRIPTION
**Pull request by RyanTG**
Pretty major style update.
The color palette is: Bright Coral; Sky Blue; Charcoal; Neutral Gray; Carbon; White.

So basically, grays and then two bright accent colors. I also re-did the logo with new colors. I can't tell if it looks good, though. It's basically uses the negative space to say the site name... and that might be a bad idea.

Overall, though, I think this looks pretty good. LMK whatcha think. I'm sure I'll do more adjusting.

### CODE REVIEW

**Comment by RyanTG** [comment]
Oh, just remembered that I moved some stuff on the About page, which may cause this test to break... I'll fix it if it does.

**Comment by scottwainstock** [comment]
@RyanTG I like that it seems simpler... easier to absorb... not wild about the "typewriter" font with it though. Also I feel like the landing page might be TOO simple now? I liked the treasure map. Maybe something in between what's there now and the treasure map would be good?

**Comment by scottwainstock** [comment]
@RyanTG Oh and I go back and forth with the logo. At first I wasn't into it, then I liked how it fit with the rest of the reskin. So, I'm not sure!

**Comment by RyanTG** [comment]
The typewriter font for the region names? That's the same font that's currently on the site, though I removed the crazy drop shadow. I'll try it with a different font. That would make one less file to load.

Yeah, I'm trying to find a way to use that treasure map somehow!

**Comment by scottwainstock** [comment]
Yeah I think it looks kind of out of place when everything has been made
more "plain". I like it fine on the current site.

**Pull request merged**
