### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by RyanTG**
I installed a fresh linux distro - manjaro - and mostly did these commits to prove that things are set up correctly. Postgres was the toughest thing. But the links I included did the job.

My tests are going well now. Maybe the problem was with an old phantomjs...

### CODE REVIEW

**Comment by RyanTG** [comment]
hmm, though I am getting two fails (locally): 
rspec ./spec/models/region_spec.rb:32 # Region#generate_daily_digest_comments_email_body should generate a string containing all machine comments from the day
rspec ./spec/models/region_spec.rb:52 # Region#generate_daily_digest_removals_email_body should generate a string containing all machine removals from the day

I've done db:migrate. Could an old data dump cause this? seems unlikely.

**Comment by bpoore** [comment]
The OSX instructions should be updated from:
open http://pbm.dev

To match the Linux:
Start server: `bundle exec rails s`
Run tests: `bundle exec rspec`

**Comment by RyanTG** [comment]
Is `selenium install` necessary still? That's what we used to use for tests. I don't know if it's used for anything else still.

What about these ones?
`curl get.pow.cx | sh`
`cd ~/.pow`

**Comment by bpoore** [comment]
I would have to try setting up the repo locally fresh to know for sure as I did do all that stuff initially- whether or not it was all necessary, I'm not certain. Your instructions for Linux other than the Linux-specific Postgres stuff seems like it should work for OSX as well. I'll try a fresh local install and get back to you.

**Comment by RyanTG** [comment]
You don't have to. If it works, it works! Scott can probably tell us about selenium.

Setting up postgres is bizarre. The instructions I wrote myself from last time were terrible. And this time I got a strange error related to the server not running (even though I'd started it). It felt like there were two ways to do the same thing, but one of them magically failed and the other magically worked. Took me a good hour last night :<

But yeah, these instructions are pretty interchangeable. But as someone who often follows instructions, it's helpful when things are pretty specific.

**Pull request merged**
