### PR TITLE
added operator name to location info

### PR DESCRIPTION
**Pull request by RyanTG**

### CODE REVIEW

**Comment by RyanTG** [comment]
That second commit is a really minor change, just to clean up the head. Do you know why we have sensor=true, rather than sensor=false (in http://maps.google.com/maps/api/js?sensor=true)? I need to look into it more, but I thought that was referring to whether the site senses the location of the user. If so, we don't use that feature.

**Comment by RyanTG** [comment]
Woah, I did NOT want that added to the pull request. Really cool how that did it automatically.

**Comment by RyanTG** [comment]
Has this been merged but not deployed?

**Comment by scottwainstock** [comment]
Y

**Pull request merged**
